services:
  pocketbase:
    build:
      context: .
      dockerfile: dockerfile
    container_name: monk_house
    env_file:
      - ./pb/.env
    volumes:
      - ./pb/pb_data:/src/pb_data
    ports:
      - "8090:8090"
    restart: unless-stopped
    networks:
      - nginx_network
networks:
  nginx_network:
    external: true
